version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - echo "Installing dependencies..."
      - pip install -r requirements.txt -t lib
  build:
    commands:
      - echo "Zipping deployment package..."
      - cd lib
      - zip -r9 ../deployment_package_weblogs.zip . -x "airflow/*" "s3_to_hive/*"
      - cd ..
      - zip -g deployment_package_weblogs.zip *.py
  post_build:
    commands:
      - echo "Uploading to S3..."
      - aws s3 cp deployment_package_weblogs.zip s3://web-logs-bucket-monthly-packages/
      - echo "Updating Lambda function via S3..."
      - aws lambda update-function-code --function-name mock-web-logs --s3-bucket web-logs-bucket-monthly-packages --s3-key deployment_package_weblogs.zip
      - echo "Copying spark script to S3 bucket"
      - aws s3 ../s3_to_hive/* s3://airflow-weblogs-spark-bucket/
      - echo "Copying airflow_to_emr file to S3 bucket"
      - aws s3 cp ../airflow/* s3://airflow-weblogs-bucket/dags/
      - echo "Deployment complete!"